services:
  postgis:
    image: postgres
    container_name: todo-api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todo-api
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo-api
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: todo-api-redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
